name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule: [cron: "45 2 * * 1"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  fmt-check:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy --all-targets

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo test

  miri:
    name: Miri
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: -Zmiri-strict-provenance
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@miri
      - name: Run cargo miri test (64-bit little endian)
        run: cargo miri test --target x86_64-unknown-linux-gnu
      - name: Run cargo miri test (64-bit big endian)
        run: cargo miri test --target mips64-unknown-linux-gnuabi64
      - name: Run cargo miri test (32-bit little endian)
        run: cargo miri test --target i686-unknown-linux-gnu
      - name: Run cargo miri test (32-bit big endian)
        run: cargo miri test --target mips-unknown-linux-gnu
